<a href="https://colab.research.google.com/github/pritishma-shakya/ai-and-machine-learning/blob/main/PritishmaShakya_2408412_Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4.1 Exercise on Functions:

Task - 1:
Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [1]:
def convert_units(conversion_type, value):
    """
    Converts between different units of measurement.

    Parameters:
    conversion_type (str): Type of conversion chosen by user
    value (float): numeric value to convert

    Returns:
    float: converted value
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084

    elif conversion_type == "ft_to_m":
        return value / 3.28084

    elif conversion_type == "kg_to_lb":
        return value * 2.20462

    elif conversion_type == "lb_to_kg":
        return value / 2.20462

    elif conversion_type == "l_to_gal":
        return value * 0.264172

    elif conversion_type == "gal_to_l":
        return value / 0.264172

    else:
        raise ValueError("Unsupported conversion type")


def main():
    print("Choose conversion type:")
    print("1: meters → feet")
    print("2: feet → meters")
    print("3: kg → pounds")
    print("4: pounds → kg")
    print("5: liters → gallons")
    print("6: gallons → liters")

    choice = input("Enter choice (1-6): ")

    try:
        value = float(input("Enter value: "))

        conversions = {
            "1": "m_to_ft",
            "2": "ft_to_m",
            "3": "kg_to_lb",
            "4": "lb_to_kg",
            "5": "l_to_gal",
            "6": "gal_to_l"
        }

        result = convert_units(conversions[choice], value)

        print("Converted value:", result)

    except ValueError:
        print("Invalid input. Please enter numeric values.")

    except KeyError:
        print("Invalid conversion option.")


main()

Choose conversion type:
1: meters → feet
2: feet → meters
3: kg → pounds
4: pounds → kg
5: liters → gallons
6: gallons → liters
Enter choice (1-6): 6
Enter value: 100
Converted value: 378.54125342579835


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [2]:
def find_sum(numbers):
    """Returns the sum of numbers"""
    return sum(numbers)


def find_average(numbers):
    """Returns the average of numbers"""
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """Returns the maximum number"""
    return max(numbers)


def find_min(numbers):
    """Returns the minimum number"""
    return min(numbers)


def main():

    try:
        nums = input("Enter numbers separated by space: ")

        numbers = [float(x) for x in nums.split()]

        if len(numbers) == 0:
            raise ValueError("List cannot be empty")

        print("Choose operation:")
        print("1 Sum")
        print("2 Average")
        print("3 Maximum")
        print("4 Minimum")

        choice = input("Enter choice: ")

        if choice == "1":
            print("Sum:", find_sum(numbers))

        elif choice == "2":
            print("Average:", find_average(numbers))

        elif choice == "3":
            print("Maximum:", find_max(numbers))

        elif choice == "4":
            print("Minimum:", find_min(numbers))

        else:
            print("Invalid choice")

    except ValueError:
        print("Invalid input. Enter numbers only.")


main()

Enter numbers separated by space: 2 4 5 6 8 10
Choose operation:
1 Sum
2 Average
3 Maximum
4 Minimum
Enter choice: 2
Average: 5.833333333333333


4.2 Exercise on List Manipulation:

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [3]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [4]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([1,2,3,4,5,6],2,4))

[3, 4, 5]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [5]:
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [6]:
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [7]:
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [8]:
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1,2,3,4,5],2))

[4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [9]:
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


4.3 Exercise on Nested List:

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [10]:
def flatten(lst):
    result = []
    for sub in lst:
        result.extend(sub)
    return result

print(flatten([[1,2],[3,4],[5]]))

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [11]:
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst,[1,2]))

6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [12]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item,list):
            total += sum_nested(item)
        else:
            total += item
    return total
print(sum_nested([[1,2],[3,[4,5]],6]))

21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [13]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item,list):
            result.append(remove_element(item,elem))
        else:
            if item != elem:
                result.append(item)
    return result

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [14]:
def find_max(lst):
    maximum = float("-inf")

    for item in lst:
        if isinstance(item,list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum,item)

    return maximum

print(find_max([[1,2],[3,[4,5]],6]))

6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [15]:
def count_occurrences(lst, elem):
    count = 0

    for item in lst:
        if isinstance(item,list):
            count += count_occurrences(item,elem)
        elif item == elem:
            count += 1

    return count

print(count_occurrences([[1,2],[2,3],[2,4]],2))

3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [16]:
def deep_flatten(lst):
    result = []

    for item in lst:
        if isinstance(item,list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [17]:
def average_nested(lst):

    flat = deep_flatten(lst)

    return sum(flat) / len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

3.5


10.1 Basic Vector and Matrix Operation with Numpy.

In [18]:
import numpy as np

# 1. Initialize an empty array with size 2X2.
arr1 = np.empty((2,2))
print("Empty array:\n",arr1)

# 2. Initialize an all one array with size 4X2.
arr2 = np.ones((4,2))
print("\nOnes array:\n",arr2)

# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
arr3 = np.full((3,3),7)
print("\nFull array:\n",arr3)

# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
arr4 = np.zeros_like(arr3)
print("\nZeros like:\n",arr4)

# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
arr5 = np.ones_like(arr3)
print("\nOnes like:\n",arr5)

# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\nConverted list to numpy array:\n",arr6)

Empty array:
 [[1.20086861e-315 0.00000000e+000]
 [1.20008047e-315 6.56018613e-310]]

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones like:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Converted list to numpy array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [19]:
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [20]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
# 4. Create a random array of size 30 and find the mean of the array.
arr = np.random.random(30)

print(arr)
print("Mean:", arr.mean())

[0.32379503 0.56387964 0.19475446 0.50423051 0.68557263 0.73108306
 0.80324016 0.23603763 0.97750946 0.76745354 0.20959865 0.71817694
 0.69128308 0.53080548 0.09418431 0.95411201 0.91179157 0.89426772
 0.50708667 0.26307075 0.16078392 0.62951902 0.10317029 0.37795551
 0.1870811  0.49506714 0.88946175 0.5347116  0.22696967 0.81767527]
Mean: 0.5328109525340048


In [45]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
arr = np.random.random((10,10))

print(arr)
print("Minimum:", arr.min())
print("Maximum:", arr.max())

[[0.73711333 0.44054903 0.26049269 0.62442179 0.09582684 0.31041173
  0.76596154 0.27143564 0.34841702 0.6100534 ]
 [0.79700879 0.09173046 0.63909959 0.85577604 0.53609162 0.16912649
  0.39363371 0.51036676 0.7714643  0.77031916]
 [0.09572382 0.98290479 0.61488451 0.95991236 0.57374474 0.78799373
  0.49750841 0.39241345 0.41109896 0.64618383]
 [0.55799877 0.86404013 0.05559089 0.00581972 0.3035976  0.82760196
  0.20287569 0.05694831 0.6483795  0.52203952]
 [0.38572484 0.07436916 0.69058853 0.14816174 0.17802384 0.96506819
  0.68969712 0.57878154 0.24814384 0.88197825]
 [0.37622775 0.82548059 0.78971938 0.03955565 0.44722191 0.93938586
  0.00612572 0.13421007 0.26937825 0.10267691]
 [0.55463323 0.67386562 0.45366771 0.45131068 0.05044636 0.61479779
  0.45849202 0.09087128 0.20474027 0.52879336]
 [0.86710455 0.76288792 0.36844691 0.66728726 0.88586842 0.07812014
  0.0761228  0.00694034 0.24918683 0.80843976]
 [0.52811888 0.81015707 0.1955316  0.9155413  0.40515911 0.84695711
  0.15259192

In [46]:
# 6. Create a zero array of size 10 and replace 5th element with 1.
arr = np.zeros(10)

arr[4] = 1

print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
# 7. Reverse an array arr = [1,2,0,0,4,0].

arr = np.array([1,2,0,0,4,0])

reverse = arr[::-1]

print(reverse)

[0 4 0 0 2 1]


In [26]:
# 8. Create a 2d array with 1 on border and 0 inside.

arr = np.ones((5,5))

arr[1:-1,1:-1] = 0

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
arr = np.zeros((8,8),dtype=int)

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

In [28]:
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print("x:\n", x)
print("y:\n", y)
print("v:", v)
print("w:", w)

x:
 [[1 2]
 [3 5]]
y:
 [[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12]


In [48]:
# 1. Add the two array.
add_xy = x + y
print("x + y:\n", add_xy)

x + y:
 [[ 6  8]
 [10 13]]


In [30]:
# 2. Subtract the two array.
sub_xy = x - y
print("x - y:\n", sub_xy)

x - y:
 [[-4 -4]
 [-4 -3]]


In [31]:
# 3. Multiply the array with any integers of your choice.
mul_x = 3 * x
mul_y = 4 * y
print("3 * x:\n", mul_x)
print("4 * y:\n", mul_y)

3 * x:
 [[ 3  6]
 [ 9 15]]
4 * y:
 [[20 24]
 [28 32]]


In [32]:
# 4. Find the square of each element of the array.
sq_x = np.square(x)
sq_y = np.square(y)
print("x^2 element-wise:\n", sq_x)
print("y^2 element-wise:\n", sq_y)

x^2 element-wise:
 [[ 1  4]
 [ 9 25]]
y^2 element-wise:
 [[25 36]
 [49 64]]


In [33]:
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("v dot w =", dot_vw)
print("x dot v =", dot_xv)
print("x dot y:\n", dot_xy)

v dot w = 219
x dot v = [29 77]
x dot y:
 [[19 22]
 [50 58]]


In [34]:
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
concat_xy_rows = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows (axis=0):\n", concat_xy_rows)

v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_vw_cols = np.concatenate((v_col, w_col), axis=1)
print("Concatenate v and w along columns:\n", concat_vw_cols)

Concatenate x and y along rows (axis=0):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


In [49]:
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
    bad_concat = np.concatenate((x, v), axis=0)
    print(bad_concat)
except ValueError as e:
    print("Error:", e)
    print("Reason: x is 2D shape", x.shape, "but v is 1D shape", v.shape,
          "→ cannot concatenate arrays with different dimensions.")

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D shape (2, 2) but v is 1D shape (2,) → cannot concatenate arrays with different dimensions.


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

In [36]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

print("A:\n", A)
print("B:\n", B)

A:
 [[3 4]
 [7 8]]
B:
 [[5 3]
 [2 1]]


In [50]:
# 1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
I = np.eye(A.shape[0])

print("A inverse:\n", A_inv)
print("A @ A_inv:\n", A @ A_inv)
print("Is A @ A_inv close to I?", np.allclose(A @ A_inv, I))

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A @ A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A @ A_inv close to I? True


In [38]:
# 2. Prove AB ̸= BA.
AB = A @ B
BA = B @ A

print("AB:\n", AB)
print("BA:\n", BA)
print("Is AB equal to BA?", np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False


In [39]:
# 3. Prove (AB)T = BTAT
left = (A @ B).T
right = B.T @ A.T

print("(AB)^T:\n", left)
print("B^T A^T:\n", right)
print("Are they equal?", np.allclose(left, right))

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Are they equal? True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [40]:
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]], dtype=float)

C = np.array([-1, -3, 9], dtype=float)

print("A_sys:\n", A_sys)
print("C:\n", C)

A_sys:
 [[ 2. -3.  1.]
 [ 1. -1.  2.]
 [ 3.  1. -1.]]
C:
 [-1. -3.  9.]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [41]:
X = np.linalg.inv(A_sys) @ C
print("Solution [x, y, z]:", X)

Solution [x, y, z]: [ 2.  1. -2.]
